#pragma once

typedef enum _WSL_DISTRIBUTION_FLAGS { 
  WSL_DISTRIBUTION_FLAGS_NONE                   = 0,
  WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP         = 1,
  WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH         = 2,
  WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING  = 4
} WSL_DISTRIBUTION_FLAGS;

#define WSL_DISTRIBUTION_FLAGS_DEFAULT WSL_DISTRIBUTION_FLAGS_ENABLE_INTEROP | WSL_DISTRIBUTION_FLAGS_APPEND_NT_PATH | WSL_DISTRIBUTION_FLAGS_ENABLE_DRIVE_MOUNTING
